// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReactUpdate from "../src/ReactUpdate.bs.js";

function Counter(Props) {
  var match = ReactUpdate.useReducer(0, (function (action, state) {
          if (action) {
            return /* Update */Block.__(0, [state - 1 | 0]);
          } else {
            return /* Update */Block.__(0, [state + 1 | 0]);
          }
        }));
  var send = match[1];
  return React.createElement("div", undefined, String(match[0]), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(send, /* Decrement */1);
                    })
                }, "-"), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(send, /* Increment */0);
                    })
                }, "+"));
}

var make = Counter;

export {
  make ,
  
}
/* react Not a pure module */
