// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReactUpdateLegacy from "../src/ReactUpdateLegacy.bs.js";

function LegacyUsage(Props) {
  var match = ReactUpdateLegacy.useReducer({
        elapsed: 0
      }, (function (action, state) {
          if (action) {
            return /* Update */Block.__(0, [{
                        elapsed: 0
                      }]);
          } else {
            return /* UpdateWithSideEffects */Block.__(1, [
                      {
                        elapsed: state.elapsed + 1 | 0
                      },
                      (function (param) {
                          var send = param.send;
                          setTimeout((function (param) {
                                  return Curry._1(send, /* Tick */0);
                                }), 1000);
                          return /* () */0;
                        })
                    ]);
          }
        }));
  var send = match[1];
  React.useEffect((function () {
          Curry._1(send, /* Tick */0);
          return ;
        }), ([]));
  return React.createElement("div", undefined, String(match[0].elapsed), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(send, /* Reset */1);
                    })
                }, "Reset"));
}

var make = LegacyUsage;

export {
  make ,
  
}
/* react Not a pure module */
